# Generated by Django 5.0.2 on 2024-09-01 12:01

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Title', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media')),
                ('Text', django_quill.fields.QuillField()),
                ('Must_read', models.BooleanField(default=False)),
                ('Read_time', models.IntegerField()),
                ('Created_date', models.DateField(auto_now=True)),
                ('Created_time', models.TimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='finished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='media')),
                ('discription', models.CharField(max_length=170)),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=300)),
                ('You_tube', models.CharField(max_length=300)),
                ('Instagram', models.CharField(max_length=300)),
                ('X', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Hotdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FutureEarnersBlog.blog')),
            ],
        ),
    ]
