# Generated by Django 5.0.2 on 2024-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureEarnersBlog', '0003_upcomingairdrops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finished',
        ),
        migrations.AlterField(
            model_name='upcomingairdrops',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
