# Generated by Django 5.0.2 on 2024-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureEarnersBlog', '0004_delete_finished_alter_upcomingairdrops_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Type',
            field=models.CharField(choices=[('normal', 'normal'), ('airdrop', 'airdrop')], default='normal', max_length=50),
        ),
    ]
